creation_rules:
    - age:
        - age1dtp68pexh38r66ggk229aah7r0uwcrfjwh9amzu2qd4qa5c4ddvs4rxzu6
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHHQ+p4FUb1FaAvDVEu0oKqH+ID/+ng3wpyEdMiNjIwp arthur.garreau98@gmail.com
stores:
    yaml:
        indent: 2
